---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tasks.github.io
  resources:
  - deploymentwithjobrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tasks.github.io
  resources:
  - deploymentwithjobrunners/finalizers
  verbs:
  - update
- apiGroups:
  - tasks.github.io
  resources:
  - deploymentwithjobrunners/status
  verbs:
  - get
  - patch
  - update
